### ISSUE TITLE
Indentation with tabs

### ISSUE THREAD

**Issue by 8lall0** [astrocorp42/san#3]
By this comment:
`# Indentation (only spaces) is allowed but not required`

We can't indent with tabs. Why? I think handling both would be useful.

**Comment by z0mbie42** [comment]
Hi, thank you for the proposal.

One of the main focus for SAN is Interoperability between multiple users.
Allowing tabs for indentation will create situations where editors will not be correctly configured and the configuration file will thus be disfigured.

For the sake of simplicity we think disallowing tabs indentations is a step forward a more simple and clear format

**Comment by 8lall0** [comment]
Hi, thank for your answer.

You have a good point, but if we think of san as a human-editable format, we have to deal with the tab-vs-space war by handling 'em both.

Everything IMHO obviously.

Cheers.

**Comment by ianremmler** [comment]
Yes, please allow tabs. To me it makes sense to use one character to indicate on level of indention. They also allow the user to control presentation. It would be fairly easy to make a tool to reformat to a standardized style if that is desirable.

Thank you for the work on SAN. It is very similar to what I have had in mind for some time to solve this type of problem.

**Comment by Timmmm** [comment]
Basically [half](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/) of developers prefer tabs. I think picking one side in the war when there isn't a good technical reason to do so is a bad idea. It makes sense for Python or YAML where indentation is significant but I think most tab users would agree that "Oh somebody mixed their indentation and the file looks a little funny" is far preferable to "Syntax error: tabs are banned because they might make the file look a bit funny".

**Comment by z0mbie42** [comment]
The problem with **tabs** is that they are **uncertain**.
For us uncertainty is the opposite of safe, or SAN aims to be a safe format.

I agree that concerning tabs it's not really uncertainty which can lead to unsafe parser, but it can lead to harder times to quickly scan a file with human eyes.

SAN was created to be easy to read, adding tab may lead to situations where it's complicated due non interoperability.

To be interoperable, tabs should be **properly configured** which add some **avoidable cognitive charge** to the task.

Furthermore we will create a SAN linter and formatter (like go fmt or rust fmt), it means that it should have been an official/idiomatic whithespace rule, which is space.

I think that the **"or"** is the enemy of the simplicity (strings can be unquoted _or_ quoted, whitespace can be spaces _or_ tabs...) because it force us to make choices which is counter productive to achieve the goal of why we are programming.

**Comment by 8lall0** [comment]
I agree about using only spaces for a "default" formatter (I would prefer tabs, but that's irrelevant).

You can say "ok, I give you the **one true way** to indent this file", but that's something I'd rather give to a formatter, golang style.

I still think that denying tabs isn't well suited for human writing and interoperability.

**Comment by Timmmm** [comment]
Tabs aren't uncertain. The display of tabs is just configurable. You may as well say text is uncertain because I can choose to use a variable with font or whatever.

In any case I have a possible solution that should make everyone happy.

Instead of outright banning tabs, just ban *mixing* tabs and spaces. The first indentation character the parser encounters determines the whitespace mode, and then if it finds the other character it is an error.

No configuration is necessary for the linter. Formatting can't look wrong. And people still get to use the only logical indentation character.

I can't see any significant downside of this scheme - at least it seems to me to be better in some ways and worse in no way than the current situation.

**Comment by defnull** [comment]
Allowing tabs would not compromise the safety of SAN, because they do not bear any semantic meaning. Indentation in SAN is optional, so a document would parse to the exact same node tree, regardless of tabs, spaces, `\n` or `\r\n`. If tabs are forbidden, why is `\r\n` allowed?

**Comment by z0mbie42** [comment]
It would parse to the same tree node, but it would need some prior configuration to be nicely displayed for humans.

Or we believe that this additional configuration, which is avoidable, incure some mental load which is bad, is error prone, and will only lead in the best case to wasted time.

The only reason of the `\r\n` is that some windows editor will natively use this characters sequence for a newline.

We think about removing this rule.

Please remind that the primary principles of SAN are **consistency** and **simplicity**

**Comment by z0mbie42** [comment]
Hi,
After some research the decision has been made to reject this proposition for the sake of simplicity and tooling.

You can find the reason above or by searching the formatting rules for almost all the modern programming languages (rust, kotlin, scala, PEP8...)

**Comment by Timmmm** [comment]
Rust, Kotlin, Scala and Python all allow tabs.

**Comment by z0mbie42** [comment]
Mixing tabs and spaces is the beginning of the apocalypse so a decision should be made for the spaces/tabs eternal fight.

The decision has been made to choose spaces over tabs.

https://kotlinlang.org/docs/reference/coding-conventions.html

https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md

https://docs.scala-lang.org/style/indentation.html

https://www.python.org/dev/peps/pep-0008/?#indentation

**Comment by Timmmm** [comment]
What about my suggestion of disallowing mixing them, but allowing all-spaces or all-tab files?

**Comment by z0mbie42** [comment]
The same problem arise: too much  complexity, edge case and not enough simplicity and homogeneity
