### ISSUE TITLE
Comparison with HOCON

### ISSUE THREAD

**Issue by maciej** [astrocorp42/san#4]
Hi,

The website compares SAN with TOML, YAML and JSON. How does it compare with [HOCON](https://github.com/lightbend/config/blob/master/HOCON.md), though?

**Comment by z0mbie42** [comment]
Hi,
We considered but didn't included HOCON because for us it's a JSON extension like HJSON or JSON5 and embedded many of it's flaws.

* duplicate keys are allowed (which is a nonsens because we don't want vicious overwrittes, or may indicate a typo
* too many `or` : comments can start with `//` **or** `#`,  `If a key is followed by {, the : or = may be omitted. So "foo" {} means "foo" : {}` etc... which will lead to too disparate configuration files.
*  we don't like the way object are merged:
```
a = { b = 1 }
# imagine 200 line
a = { c = 2 }
```
is a good way to create **incomprehensible** files!

**Comment by maciej** [comment]
Thank you for taking the time sum up the differences! That's a detailed answer!
